import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import {
  ArrowsClockwise,
  Bell,
  BookOpen,
  ChartBar,
  Clock,
  Code,
  CreditCard,
  Cube,
  Crop,
  Database,
  Eraser,
  FileImage,
  FilePdf,
  Fingerprint,
  FlowArrow,
  Key,
  Images,
  Lightning,
  LockKey,
  OpenAiLogo,
  Perspective,
  QrCode,
  Queue,
  Printer,
  Receipt,
  Rows,
  ShieldCheck,
  Sparkle,
  SquaresFour,
  Stack,
  Table,
  Truck,
  VideoCamera,
} from "@phosphor-icons/react/dist/ssr";
import {
  siAliexpress,
  siAnthropic,
  siAppstore,
  siClerk,
  siCloudflare,
  siExpo,
  siFramer,
  siGoogle,
  siGoogleads,
  siGoogleanalytics,
  siGooglegemini,
  siGooglemaps,
  siHeroui,
  siMercadopago,
  siMeta,
  siModelcontextprotocol,
  siNextdotjs,
  siOpenrouter,
  siPostgresql,
  siPwa,
  siPosthog,
  siPrisma,
  siRadixui,
  siReact,
  siReacthookform,
  siReactquery,
  siReplicate,
  siResend,
  siShadcnui,
  siStripe,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siUpstash,
  siVercel,
  siWhatsapp,
  siZod,
  type SimpleIcon,
} from "simple-icons";

export type Glyph = SimpleIcon | PhosphorIcon;

// First match wins, so specific phrases sit above the brands they mention.
// Brands use Simple Icons; ideas without a logo (migrations, cron, locks) use Phosphor.
const rules: [RegExp, Glyph][] = [
  [/push/i, Bell],
  [/Whisper/, OpenAiLogo],
  [/PWA/, siPwa],
  [/FIFO/, Stack],
  [/ledger/, Rows],
  [/ESC\/POS|tickets/, Printer],
  [/PDF/, FilePdf],
  [/Excel/, Table],
  [/deploys/, Stack],
  [/AliExpress/, siAliexpress],
  [/Base UI/, Cube],
  [/WhatsApp/, siWhatsapp],
  [/per brand/, Stack],
  [/Job queue|outbox/, Queue],
  [/cron/i, Clock],
  [/React Hook Form/, siReacthookform],
  [/React Native|Reanimated|React Compiler/, siReact],
  [/React Flow/, FlowArrow],
  [/TanStack/, siReactquery],
  [/Expo|EAS/, siExpo],
  [/Next\.js|App Router/, siNextdotjs],
  [/Cache Components|use cache|Prefetching/, Lightning],
  [/updateTag|revalidatePath|regenerated/, ArrowsClockwise],
  [/Server Actions|Route handlers|SDK queries|Plain SQL/, Code],
  [/loading\.tsx/, Rows],
  [/TypeScript/, siTypescript],
  [/Tailwind/, siTailwindcss],
  [/Radix/, siRadixui],
  [/shadcn/, siShadcnui],
  [/HeroUI/, siHeroui],
  [/^Motion$/, siFramer],
  [/Recharts/, ChartBar],
  [/Zustand/, Cube],
  [/Zod/, siZod],
  [/^React/, siReact],
  [/Row-level|allowlist/, ShieldCheck],
  [/row locks|RPCs/, LockKey],
  [/Generated columns/, Table],
  [/migrations/, Database],
  [/R2/, siCloudflare],
  [/Supabase/, siSupabase],
  [/InsForge/, Database],
  [/Postgre/, siPostgresql],
  [/Prisma/, siPrisma],
  [/Upstash/, siUpstash],
  [/argon2|API keys/, Key],
  [/OIDC/, Fingerprint],
  [/AI SDK|AI Gateway|Vercel/, siVercel],
  [/Anthropic/, siAnthropic],
  [/OpenAI|gpt|GPT/, OpenAiLogo],
  [/Gemini|GenAI/, siGooglegemini],
  [/OpenRouter/, siOpenrouter],
  [/MCP/, siModelcontextprotocol],
  [/Replicate/, siReplicate],
  [/Kling|Seedance/, VideoCamera],
  [/Flux|Ideogram|Higgsfield|^Fal$|Auto-Toon|Seedream/, Sparkle],
  [/SSRF|leak/, ShieldCheck],
  [/check scripts/, Code],
  [/Swatches|crop/i, Crop],
  [/Watermark/i, Eraser],
  [/Perspective/, Perspective],
  [/renders/i, Images],
  [/Stripe/, siStripe],
  [/MercadoPago/, siMercadopago],
  [/Conekta|Aplazo/, CreditCard],
  [/CFDI|invoic/, Receipt],
  [/Skydropx|shipping/, Truck],
  [/in-app|App Store/i, siAppstore],
  [/Resend/, siResend],
  [/Meta/, siMeta],
  [/Google (Places|Maps)/, siGooglemaps],
  [/GA4/, siGoogleanalytics],
  [/Google Ads/, siGoogleads],
  [/AVIF|WebP|HEIC/, FileImage],
  [/jsPDF/, FilePdf],
  [/QR/, QrCode],
  [/Flip-book/, BookOpen],
  [/Clerk/, siClerk],
  [/Google sign-in/, siGoogle],
  [/PostHog/, siPosthog],
];

export function iconFor(label: string): Glyph {
  return rules.find(([re]) => re.test(label))?.[1] ?? SquaresFour;
}

export { SquaresFour as fallbackIcon };
